# Refer to https://wiki.hyprland.org/Configuring/Variables/
# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 5,5,5,5 
    gaps_out =9,9,9,9 
    # gaps_out = 20

    border_size = 2
    # no_border_on_floating = true

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)
    
    # col.active_border = rgba(fbf1c7ee) rgba(fe8019ee)  45deg
    # col.active_border = rgba(a89984ee) rgba(fbf1c7ee) 45deg
    # col.active_border = rgba(ebdbb213)
    # col.active_border = rgba(ebdbb213)
    # col.active_border = rgba(d5c4a170) # default: 0xff32b4ff
    # col.inactive_border = rgba(3c383600)

    col.inactive_border = rgba(ebdbb210)
    col.active_border = rgba(ebdbb20A)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true 
    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = hy3 

}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 12

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.7

    border_part_of_window = false 

    # drop_shadow = false
    # shadow_range = 4
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        new_optimizations = true
        size = 4
        passes = 3
        ignore_opacity = true
        vibrancy = 0.5
        # xray = true
        noise = 0.015
        # contrast = 0.45

        # vibrancy_darkness = 0.3
    }
}

source = ./animations/minimal-2.conf
